In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
import plotly.express as px
from sklearn.preprocessing import OrdinalEncoder
from dataprep.eda import create_report

In [ ]:
!pip install dataprep

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 27.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 60.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 kB 18.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 82.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 73.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 71.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 93.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 764.0/764.0 kB 48.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 83.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 75.7 MB/s eta 0:00:00
  Created wheel for sqlalchemy: filena

In [ ]:
df=pd.read_csv("/content/diabetes_prediction_dataset.csv.zip")
df.head()
df.gender.unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [ ]:
encode=OrdinalEncoder()
df.gender=encode.fit_transform(df[["gender"]])
df.gender.unique()

array([0., 1., 2.])

In [ ]:
df.smoking_history.unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [ ]:
encode1=OrdinalEncoder()
df.smoking_history=encode1.fit_transform(df[["smoking_history"]])
df.smoking_history.unique()

array([4., 0., 1., 3., 2., 5.])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  float64
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  float64
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(5), int64(4)
memory usage: 6.9 MB


In [ ]:
df.diabetes.value_counts()


0    91500
1     8500
Name: diabetes, dtype: int64

In [ ]:
x=df.drop("diabetes",axis=1)
y=df["diabetes"]

In [ ]:
x.shape,y.shape

((100000, 8), (100000,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
x_train.shape,y_train.shape

((75000, 8), (75000,))

In [ ]:
x_test.shape,y_test.shape
y_test.value_counts()

0    22859
1     2141
Name: diabetes, dtype: int64

In [ ]:
from sklearn.tree import DecisionTreeClassifier          #Decision tree algorithm
model=DecisionTreeClassifier().fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)



0.95124

In [ ]:
from sklearn.ensemble import RandomForestClassifier              #random forest
model1=RandomForestClassifier().fit(x_train,y_train)
y_pred1=model1.predict(x_test)
accuracy_score(y_test,y_pred1)

0.97004

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy=accuracy_score(y_test,y_pred)
accuracy
confusion=confusion_matrix(y_test,y_pred)
confusion

array([[22223,   636],
       [  568,  1573]])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier        #AdaBoostClassifier
model2=AdaBoostClassifier().fit(x_train,y_train)
y_pred2=model2.predict(x_test)
accuracy_score(y_test,y_pred2)

0.97164

In [ ]:
from sklearn.naive_bayes import CategoricalNB              #naive_bayes
model3= CategoricalNB().fit(x_train, y_train)
y_pred3=model3.predict(x_test)
accuracy_score(y_test,y_pred3)


0.9636

In [ ]:
from sklearn.linear_model import LogisticRegression             #LogisticRegression
model4 = LogisticRegression().fit(x_train, y_train)
y_pred4=model4.predict(x_test)
accuracy_score(y_test,y_pred4)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95084

In [ ]:
from sklearn.pipeline import make_pipeline                   #Support Vector Machines
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
modelinfo = make_pipeline(StandardScaler(), SVC(gamma='auto'))
model6=modelinfo.fit(x_train, y_train)
# Pipeline(steps=[('standardscaler', StandardScaler()),
#                 ('svc', SVC(gamma='auto'))])
y_pred5=model6.predict(x_test)
accuracy_score(y_test,y_pred5)

0.96312

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier       #GradientBoostingClassifier
model7 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
  max_depth=1, random_state=0).fit(x_train, y_train)
y_pred6=model7.predict(x_test)
accuracy_score(y_test,y_pred6)

0.97184

In [ ]:
from sklearn.neighbors import KNeighborsClassifier                        #Kneighbours
model8 = KNeighborsClassifier(n_neighbors=3).fit(x_train, y_train)
y_pred7=model8.predict(x_test)
accuracy_score(y_test,y_pred7)

0.95104

In [ ]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis     #QuadraticDiscriminantAnalysis
model9=QuadraticDiscriminantAnalysis().fit(x_train, y_train)
y_pred8=model9.predict(x_test)
accuracy_score(y_test,y_pred8)


0.90832

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis   #LinearDiscriminantAnalysis
model10= LinearDiscriminantAnalysis().fit(x_train, y_train)
y_pred9=model10.predict(x_test)
accuracy_score(y_test,y_pred9)

0.95576

In [ ]:
lister={'decision tree':95.124,'LinearDiscriminantAnalysis':95.576,'QuadraticDiscriminantAnalysis':90.832,'Kneighbours':95.104,'GradientBoostingClassifier':97.184,'Support Vector Machines':96.312,'LogisticRegression':95.084,'naive_bayes':96.36,'AdaBoostClassifier':97.164,'random forest':97.004}

In [ ]:
lister1=pd.DataFrame({'algorithms':['decision tree','LinearDiscriminantAnalysis','QuadraticDiscriminantAnalysis','Kneighbours','GradientBoostingClassifier','Support Vector Machines','LogisticRegression','naive_bayes','AdaBoostClassifier','random forest'],
                     'accuracy':[95.124,95.576,90.832,95.104,97.184,96.312,95.084,96.36,97.164,97.004]},
                     index=([1,2,3,4,5,6,7,8,9,10]))

In [ ]:
lister1

algorithms  accuracy
1                   decision tree    95.124
2      LinearDiscriminantAnalysis    95.576
3   QuadraticDiscriminantAnalysis    90.832
4                     Kneighbours    95.104
5      GradientBoostingClassifier    97.184
6         Support Vector Machines    96.312
7              LogisticRegression    95.084
8                     naive_bayes    96.360
9              AdaBoostClassifier    97.164
10                  random forest    97.004